version: '3.8'
services:
  db:
    image: postgres
    container_name: xpense-tracker-db
    environment:
      POSTGRES_USER: xpense_admin
      POSTGRES_PASSWORD: xpenseTracker1234
      POSTGRES_DB: xpense_tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
